version: "3"

services:
  proxy:
    image: glud/transproxy:latest
    networks:
      - outside
      - inside
    environment:
      PROXY_HOSTS: 10.20.4.15:3128
      TRANSPARENT_PROXY_PORT: :3128
#    volumes:
#      data:/home
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    cap_add:
      - NET_ADMIN

  cliente1:
     image: glud/testubuntu:latest
     command: tail -f /dev/null
     networks:
       - inside
     cap_add:
       - NET_ADMIN
 
  cliente2:
     image: centos
     command: tail -f /dev/null
     networks:
       - inside
     cap_add:
       - NET_ADMIN

networks:
  inside:
    internal: true
  outside:

volumes:
  data:
